blank_issues_enabled: false
issue_templates:
  - name: "Bug report"
    about: "Report a bug or unexpected behavior in Equilibrium."
    template: "bug_report.yml"
  - name: "Feature request"
    about: "Suggest a new feature or improvement to enhance Equilibrium."
    template: "feature_request.yml"
